services:

  swagger:
    build:
      context: ..
      dockerfile_inline: |
        FROM golang:1.26.4-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - .:/code